# Generated by Django 4.2.28 on 2026-02-06 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='股票名称')),
                ('symbol', models.CharField(max_length=20, unique=True, verbose_name='股票代码')),
                ('keywords', models.TextField(default='[]', verbose_name='关键词')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '监控股票',
                'verbose_name_plural': '监控股票',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='SentimentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('sentiment_score', models.FloatField(default=0, verbose_name='情感分数')),
                ('sentiment_label', models.CharField(default='中性', max_length=10, verbose_name='情感标签')),
                ('hot_score', models.FloatField(default=0, verbose_name='热度分数')),
                ('news_count', models.IntegerField(default=0, verbose_name='新闻数')),
                ('report_count', models.IntegerField(default=0, verbose_name='研报数')),
                ('announcement_count', models.IntegerField(default=0, verbose_name='公告数')),
                ('discussion_count', models.IntegerField(default=0, verbose_name='讨论数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock', verbose_name='股票')),
            ],
            options={
                'verbose_name': '舆情数据',
                'verbose_name_plural': '舆情数据',
                'ordering': ['-date', '-hot_score'],
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('pub_date', models.DateField(verbose_name='发布日期')),
                ('org', models.CharField(max_length=100, verbose_name='机构')),
                ('rating', models.CharField(blank=True, max_length=50, verbose_name='评级')),
                ('url', models.URLField(verbose_name='链接')),
                ('sentiment_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.sentimentdata')),
            ],
            options={
                'verbose_name': '研报',
                'verbose_name_plural': '研报',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('pub_date', models.DateField(verbose_name='发布日期')),
                ('source', models.CharField(max_length=50, verbose_name='来源')),
                ('url', models.URLField(verbose_name='链接')),
                ('sentiment_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='api.sentimentdata')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('pub_date', models.DateField(verbose_name='发布日期')),
                ('url', models.URLField(verbose_name='链接')),
                ('sentiment_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='api.sentimentdata')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-pub_date'],
            },
        ),
    ]
