# Generated by Django 4.2.29 on 2026-03-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='extra_links',
            field=models.TextField(default='[]', verbose_name='额外链接'),
        ),
    ]
