# Generated by Django 4.2.29 on 2026-04-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stock_extra_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundamentalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='股票代码')),
                ('date', models.DateField(verbose_name='报告日期')),
                ('pe', models.FloatField(default=0, verbose_name='TTM市盈率')),
                ('pb', models.FloatField(default=0, verbose_name='市净率')),
                ('roi', models.FloatField(default=0, verbose_name='ROI')),
                ('dividend_yield', models.FloatField(default=0, verbose_name='股息率')),
                ('ttm_profit', models.FloatField(default=0, verbose_name='TTM净利润')),
                ('total_equity', models.FloatField(default=0, verbose_name='归母净资产')),
                ('price', models.FloatField(default=0, verbose_name='价格')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '基本面快照',
                'verbose_name_plural': '基本面快照',
                'ordering': ['-date'],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
