# Generated by Django 4.2.29 on 2026-04-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fundamentalsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='valuation_config',
            field=models.TextField(default='{}', verbose_name='估值配置'),
        ),
    ]
