# Generated by Django 4.2.29 on 2026-04-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stock_valuation_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='行业'),
        ),
        migrations.AddField(
            model_name='stock',
            name='peer_symbols',
            field=models.TextField(default='[]', verbose_name='同行股票代码'),
        ),
    ]
