# Generated by Django 6.0.3 on 2026-05-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_stockscreenersnapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockscreenersnapshot',
            new_name='api_stocksc_snapsho_c0c9b0_idx',
            old_name='api_stocksc_snapsho_9bf31c_idx',
        ),
        migrations.RenameIndex(
            model_name='stockscreenersnapshot',
            new_name='api_stocksc_snapsho_f89866_idx',
            old_name='api_stocksc_snapsho_a3ec85_idx',
        ),
        migrations.RenameIndex(
            model_name='stockscreenersnapshot',
            new_name='api_stocksc_snapsho_38d484_idx',
            old_name='api_stocksc_snapsho_640c9a_idx',
        ),
        migrations.RenameIndex(
            model_name='stockscreenersnapshot',
            new_name='api_stocksc_snapsho_6fe419_idx',
            old_name='api_stocksc_snapsho_766b06_idx',
        ),
        migrations.AddField(
            model_name='stockscreenersnapshot',
            name='cfo_yield',
            field=models.FloatField(default=0, verbose_name='经营现金流收益率'),
        ),
        migrations.AddField(
            model_name='stockscreenersnapshot',
            name='net_cash_ratio',
            field=models.FloatField(default=0, verbose_name='净现比'),
        ),
        migrations.AddIndex(
            model_name='stockscreenersnapshot',
            index=models.Index(fields=['snapshot_date', 'net_cash_ratio'], name='api_stocksc_snapsho_c6511a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockscreenersnapshot',
            index=models.Index(fields=['snapshot_date', 'cfo_yield'], name='api_stocksc_snapsho_3fc072_idx'),
        ),
    ]
