# Generated by Django 4.2.29 on 2026-06-03 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_api_stocksc_snapsho_9bf31c_idx_api_stocksc_snapsho_c0c9b0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='默认组合', max_length=100, verbose_name='组合名称')),
                ('total_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='总资金')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认组合')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '投资组合',
                'verbose_name_plural': '投资组合',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_pct', models.FloatField(default=0, verbose_name='配置比例(%)')),
                ('share_count', models.IntegerField(default=0, verbose_name='持股数量')),
                ('buy_price', models.FloatField(blank=True, null=True, verbose_name='买入价格')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='api.portfolio', verbose_name='组合')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock', verbose_name='股票')),
            ],
            options={
                'verbose_name': '组合持仓',
                'verbose_name_plural': '组合持仓',
                'ordering': ['-allocation_pct'],
                'unique_together': {('portfolio', 'stock')},
            },
        ),
    ]
