# Generated by Django 4.2.29 on 2026-06-03 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_portfolio_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('sentiment_low', '情感分数低于阈值'), ('sentiment_high', '情感分数高于阈值'), ('pe_low', 'PE 低于阈值'), ('pe_high', 'PE 高于阈值'), ('pb_low', 'PB 低于阈值'), ('pb_high', 'PB 高于阈值'), ('dividend_yield_high', '股息率高于阈值'), ('hot_spike', '热度飙升')], max_length=30, verbose_name='规则类型')),
                ('threshold', models.FloatField(verbose_name='阈值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='api.stock', verbose_name='股票')),
            ],
            options={
                'verbose_name': '告警规则',
                'verbose_name_plural': '告警规则',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='触发时间')),
                ('message', models.TextField(verbose_name='告警消息')),
                ('value', models.FloatField(default=0, verbose_name='触发值')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.alertrule', verbose_name='规则')),
            ],
            options={
                'verbose_name': '告警日志',
                'verbose_name_plural': '告警日志',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
