# Generated by Django 4.2.29 on 2026-06-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_alert_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='urls',
            field=models.TextField(blank=True, default='[]', verbose_name='所有链接'),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='链接'),
        ),
    ]
