# Generated by Django 6.0.3 on 2026-06-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_news_urls_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='rule_type',
            field=models.CharField(choices=[('sentiment_low', '情感分数低于阈值'), ('sentiment_high', '情感分数高于阈值'), ('pe_low', 'PE 低于阈值'), ('pe_high', 'PE 高于阈值'), ('pb_low', 'PB 低于阈值'), ('pb_high', 'PB 高于阈值'), ('dividend_yield_high', '股息率高于阈值'), ('hot_spike', '热度飙升'), ('margin_decline', '毛利率连续下滑'), ('receivable_surge', '应收账款增速超营收'), ('cfo_negative', '经营现金流转负'), ('price_target', '价格到达目标价'), ('pe_percentile', 'PE 进入低分位'), ('volume_anomaly', '成交量异常放大')], max_length=30, verbose_name='规则类型'),
        ),
    ]
