# Generated by Django 6.0.3 on 2026-06-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_alertrule_rule_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketValuationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(unique=True, verbose_name='日期')),
                ('pe_median', models.FloatField(default=0, verbose_name='PE 中位数')),
                ('pb_median', models.FloatField(default=0, verbose_name='PB 中位数')),
                ('pe_mean', models.FloatField(default=0, verbose_name='PE 均值')),
                ('pb_mean', models.FloatField(default=0, verbose_name='PB 均值')),
                ('stock_count', models.IntegerField(default=0, verbose_name='有效股票数')),
                ('pe_gt_zero_count', models.IntegerField(default=0, verbose_name='PE>0 股票数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '市场估值快照',
                'verbose_name_plural': '市场估值快照',
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
