# Generated by Django 6.0.3 on 2026-06-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_marketvaluationsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketvaluationsnapshot',
            name='board',
            field=models.CharField(default='all', help_text='行业名(如银行/医药生物)、指数名(如上证/沪深300)、或 all', max_length=50, verbose_name='板块/指数'),
        ),
        migrations.AlterField(
            model_name='marketvaluationsnapshot',
            name='snapshot_date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterUniqueTogether(
            name='marketvaluationsnapshot',
            unique_together={('snapshot_date', 'board')},
        ),
    ]
