# Generated by Django 4.2.29 on 2026-06-24 02:00

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_marketvaluationsnapshot_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='extra_links',
            field=api.models.JSONTextField(default=list, verbose_name='额外链接'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='keywords',
            field=api.models.JSONTextField(default=list, verbose_name='关键词'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='peer_symbols',
            field=api.models.JSONTextField(default=list, verbose_name='同行股票代码'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='valuation_config',
            field=api.models.JSONTextField(default=dict, verbose_name='估值配置'),
        ),
    ]
