# Generated by Django 4.2.29 on 2026-07-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_stock_extra_links_alter_stock_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockscreenersnapshot',
            name='fcf_yield',
            field=models.FloatField(default=0, verbose_name='自由现金流收益率'),
        ),
        migrations.AddIndex(
            model_name='stockscreenersnapshot',
            index=models.Index(fields=['snapshot_date', 'fcf_yield'], name='api_stocksc_snapsho_c0dfa3_idx'),
        ),
    ]
