# Generated by Django 6.0.3 on 2026-08-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_screener_add_fcf_yield'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='现金余额'),
        ),
    ]
